/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author pc
 */
public class PnlCreditosJuego extends javax.swing.JPanel {

    /**
     * Creates new form PnlCreditos
     */
    public PnlCreditosJuego() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblLogoEPN = new javax.swing.JLabel();
        lblLogoFIS = new javax.swing.JLabel();
        lblIntegrantes = new javax.swing.JLabel();
        lblMishelRamirez = new javax.swing.JLabel();
        lblMauricioMorales = new javax.swing.JLabel();
        lblDanielLorences = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlFondoAzulSuperior = new javax.swing.JPanel();
        pnlFondoAzulDerecho = new javax.swing.JPanel();

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoEPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Escudo_de_la_Escuela_Politécnica_Nacional.png"))); // NOI18N
        pnlFondo.add(lblLogoEPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblLogoFIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo-FIS.png"))); // NOI18N
        pnlFondo.add(lblLogoFIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        lblIntegrantes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIntegrantes.setText("Integrantes");
        pnlFondo.add(lblIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblMishelRamirez.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMishelRamirez.setText("Michelle Nicole Ramirez");
        pnlFondo.add(lblMishelRamirez, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        lblMauricioMorales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMauricioMorales.setText("Mauricio Morales");
        pnlFondo.add(lblMauricioMorales, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        lblDanielLorences.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDanielLorences.setText("Daniel Lorences");
        pnlFondo.add(lblDanielLorences, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));
        pnlFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, 10));

        pnlFondoAzulSuperior.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlFondoAzulSuperiorLayout = new javax.swing.GroupLayout(pnlFondoAzulSuperior);
        pnlFondoAzulSuperior.setLayout(pnlFondoAzulSuperiorLayout);
        pnlFondoAzulSuperiorLayout.setHorizontalGroup(
            pnlFondoAzulSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        pnlFondoAzulSuperiorLayout.setVerticalGroup(
            pnlFondoAzulSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnlFondo.add(pnlFondoAzulSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlFondoAzulDerecho.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlFondoAzulDerechoLayout = new javax.swing.GroupLayout(pnlFondoAzulDerecho);
        pnlFondoAzulDerecho.setLayout(pnlFondoAzulDerechoLayout);
        pnlFondoAzulDerechoLayout.setHorizontalGroup(
            pnlFondoAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        pnlFondoAzulDerechoLayout.setVerticalGroup(
            pnlFondoAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        pnlFondo.add(pnlFondoAzulDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDanielLorences;
    private javax.swing.JLabel lblIntegrantes;
    private javax.swing.JLabel lblLogoEPN;
    private javax.swing.JLabel lblLogoFIS;
    private javax.swing.JLabel lblMauricioMorales;
    private javax.swing.JLabel lblMishelRamirez;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFondoAzulDerecho;
    private javax.swing.JPanel pnlFondoAzulSuperior;
    // End of variables declaration//GEN-END:variables
}
