package vista;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
import modelo.Jugador;


public class PnlRegistroPartidas extends javax.swing.JPanel {

    static DefaultTableModel dtm;
    public static String nombreGanador;
    public static String nombreSegundoLugar;

    public PnlRegistroPartidas() {
        initComponents();
        dtm = new DefaultTableModel();
        dtm.addColumn("Primer lugar");
        dtm.addColumn("Segundo lugar");
        tblRegistroJugadores.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroJugadores = new javax.swing.JTable();
        pnlFondoAzulSuperior = new javax.swing.JPanel();
        pnlFondoAzulDerecho = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblRegistroJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistroJugadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 290, 500));

        pnlFondoAzulSuperior.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlFondoAzulSuperiorLayout = new javax.swing.GroupLayout(pnlFondoAzulSuperior);
        pnlFondoAzulSuperior.setLayout(pnlFondoAzulSuperiorLayout);
        pnlFondoAzulSuperiorLayout.setHorizontalGroup(
            pnlFondoAzulSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        pnlFondoAzulSuperiorLayout.setVerticalGroup(
            pnlFondoAzulSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(pnlFondoAzulSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlFondoAzulDerecho.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlFondoAzulDerechoLayout = new javax.swing.GroupLayout(pnlFondoAzulDerecho);
        pnlFondoAzulDerecho.setLayout(pnlFondoAzulDerechoLayout);
        pnlFondoAzulDerechoLayout.setHorizontalGroup(
            pnlFondoAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        pnlFondoAzulDerechoLayout.setVerticalGroup(
            pnlFondoAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        add(pnlFondoAzulDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método guarda el jugador que ganó la partida
     * @param ganador 
     */
    public static void guardarGanador(String ganador) {
        System.out.println(ganador);
        nombreGanador = ganador;
    }

    /**
     * Este método guarda el jugador que quedó en segundo lugar en la partida
     * @param segundoLugar 
     */
    public static void guardarSegundoLugar(String segundoLugar) {
        System.out.println(segundoLugar);
        nombreSegundoLugar = segundoLugar;
    }

    /**
     * Este método genera la tabla de resultados de las partidas
     */
    public void generarTabla() {
        FrmChessGame.jugadores.add(new ArrayList<>(Arrays.asList(nombreGanador, nombreSegundoLugar)));
        System.out.println(FrmChessGame.jugadores);

        for (int i = 0; i < FrmChessGame.jugadores.size(); i++) {
            boolean procesado = false;
            for (int j = 0; j < FrmChessGame.jugadores.get(i).size(); j++) {
                if (!procesado) {
                    String[] fila = new String[2];
                    fila[0] = FrmChessGame.jugadores.get(i).get(0);
                    fila[1] = FrmChessGame.jugadores.get(i).get(1);
                    dtm.addRow(fila);
                    procesado = true;
                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlFondoAzulDerecho;
    private javax.swing.JPanel pnlFondoAzulSuperior;
    private javax.swing.JTable tblRegistroJugadores;
    // End of variables declaration//GEN-END:variables
}
