/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Image;
import javax.swing.ImageIcon;
import modelo.Peon;
import modelo.Tablero;

/**
 *
 * @author pc
 */
public class PnlTableroBotones extends javax.swing.JPanel {

    Peon peon;
    Tablero tableroA = new Tablero();
    ;
    static String[][] tablero = new String[8][8];
    static String posicionAntigua;
    static String posicionNueva;
    static String posicionActual;

    /**
     * Creates new form PnlTableroBotonesRaros
     */
    public PnlTableroBotones() {
        initComponents();
        iniciarTablero();
        tableroA.setTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoTablero = new javax.swing.JPanel();
        btnH1 = new javax.swing.JToggleButton();
        btnH2 = new javax.swing.JToggleButton();
        btnH3 = new javax.swing.JToggleButton();
        btnH4 = new javax.swing.JToggleButton();
        btnH5 = new javax.swing.JToggleButton();
        btnH6 = new javax.swing.JToggleButton();
        btnH7 = new javax.swing.JToggleButton();
        btnH8 = new javax.swing.JToggleButton();
        btnG1 = new javax.swing.JToggleButton();
        btnG2 = new javax.swing.JToggleButton();
        btnG3 = new javax.swing.JToggleButton();
        btnG4 = new javax.swing.JToggleButton();
        btnG5 = new javax.swing.JToggleButton();
        btnG6 = new javax.swing.JToggleButton();
        btnG7 = new javax.swing.JToggleButton();
        btnG8 = new javax.swing.JToggleButton();
        btnF1 = new javax.swing.JToggleButton();
        btnF2 = new javax.swing.JToggleButton();
        btnF3 = new javax.swing.JToggleButton();
        btnF4 = new javax.swing.JToggleButton();
        btnF5 = new javax.swing.JToggleButton();
        btnF6 = new javax.swing.JToggleButton();
        btnF7 = new javax.swing.JToggleButton();
        btnF8 = new javax.swing.JToggleButton();
        btnE1 = new javax.swing.JToggleButton();
        btnE2 = new javax.swing.JToggleButton();
        btnE3 = new javax.swing.JToggleButton();
        btnE4 = new javax.swing.JToggleButton();
        btnE5 = new javax.swing.JToggleButton();
        btnE6 = new javax.swing.JToggleButton();
        btnE7 = new javax.swing.JToggleButton();
        btnE8 = new javax.swing.JToggleButton();
        btnD1 = new javax.swing.JToggleButton();
        btnD2 = new javax.swing.JToggleButton();
        btnD3 = new javax.swing.JToggleButton();
        btnD4 = new javax.swing.JToggleButton();
        btnD5 = new javax.swing.JToggleButton();
        btnD6 = new javax.swing.JToggleButton();
        btnD7 = new javax.swing.JToggleButton();
        btnD8 = new javax.swing.JToggleButton();
        btnC1 = new javax.swing.JToggleButton();
        btnC2 = new javax.swing.JToggleButton();
        btnC3 = new javax.swing.JToggleButton();
        btnC4 = new javax.swing.JToggleButton();
        btnC5 = new javax.swing.JToggleButton();
        btnC6 = new javax.swing.JToggleButton();
        btnC7 = new javax.swing.JToggleButton();
        btnC8 = new javax.swing.JToggleButton();
        btnB1 = new javax.swing.JToggleButton();
        btnB2 = new javax.swing.JToggleButton();
        btnB3 = new javax.swing.JToggleButton();
        btnB4 = new javax.swing.JToggleButton();
        btnB5 = new javax.swing.JToggleButton();
        btnB6 = new javax.swing.JToggleButton();
        btnB7 = new javax.swing.JToggleButton();
        btnB8 = new javax.swing.JToggleButton();
        btnA1 = new javax.swing.JToggleButton();
        btnA2 = new javax.swing.JToggleButton();
        btnA3 = new javax.swing.JToggleButton();
        btnA4 = new javax.swing.JToggleButton();
        btnA5 = new javax.swing.JToggleButton();
        btnA6 = new javax.swing.JToggleButton();
        btnA7 = new javax.swing.JToggleButton();
        btnA8 = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlFondoTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnH1.setBackground(new java.awt.Color(204, 204, 204));
        btnH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreBlanca.png"))); // NOI18N
        btnH1.setBorder(null);
        btnH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 70, 70));

        btnH2.setBackground(new java.awt.Color(126, 162, 214));
        btnH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnH2.setBorder(null);
        btnH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 70, 70));

        btnH3.setBackground(new java.awt.Color(204, 204, 204));
        btnH3.setBorder(null);
        btnH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH3ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 70, 70));

        btnH4.setBackground(new java.awt.Color(126, 162, 214));
        btnH4.setBorder(null);
        btnH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH4ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 70, 70));

        btnH5.setBackground(new java.awt.Color(204, 204, 204));
        btnH5.setBorder(null);
        pnlFondoTablero.add(btnH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 70, 70));

        btnH6.setBackground(new java.awt.Color(126, 162, 214));
        btnH6.setBorder(null);
        pnlFondoTablero.add(btnH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 70, 70));

        btnH7.setBackground(new java.awt.Color(204, 204, 204));
        btnH7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnH7.setBorder(null);
        btnH7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH7ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnH7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 70, 70));

        btnH8.setBackground(new java.awt.Color(126, 162, 214));
        btnH8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreNegra.png"))); // NOI18N
        btnH8.setBorder(null);
        pnlFondoTablero.add(btnH8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 70, 70));

        btnG1.setBackground(new java.awt.Color(126, 162, 214));
        btnG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoBlanco.png"))); // NOI18N
        btnG1.setBorder(null);
        pnlFondoTablero.add(btnG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 70, 70));

        btnG2.setBackground(new java.awt.Color(204, 204, 204));
        btnG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnG2.setBorder(null);
        btnG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 70, 70));

        btnG3.setBackground(new java.awt.Color(126, 162, 214));
        btnG3.setBorder(null);
        pnlFondoTablero.add(btnG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 70, 70));

        btnG4.setBackground(new java.awt.Color(204, 204, 204));
        btnG4.setBorder(null);
        pnlFondoTablero.add(btnG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 70, 70));

        btnG5.setBackground(new java.awt.Color(126, 162, 214));
        btnG5.setBorder(null);
        pnlFondoTablero.add(btnG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 70, 70));

        btnG6.setBackground(new java.awt.Color(204, 204, 204));
        btnG6.setBorder(null);
        pnlFondoTablero.add(btnG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 70, 70));

        btnG7.setBackground(new java.awt.Color(126, 162, 214));
        btnG7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnG7.setBorder(null);
        btnG7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG7ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 70, 70));

        btnG8.setBackground(new java.awt.Color(204, 204, 204));
        btnG8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoNegro.png"))); // NOI18N
        btnG8.setBorder(null);
        pnlFondoTablero.add(btnG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 70));

        btnF1.setBackground(new java.awt.Color(204, 204, 204));
        btnF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilBlanco.png"))); // NOI18N
        btnF1.setBorder(null);
        btnF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 70, 70));

        btnF2.setBackground(new java.awt.Color(126, 162, 214));
        btnF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnF2.setBorder(null);
        btnF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 70, 70));

        btnF3.setBackground(new java.awt.Color(204, 204, 204));
        btnF3.setBorder(null);
        pnlFondoTablero.add(btnF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 70, 70));

        btnF4.setBackground(new java.awt.Color(126, 162, 214));
        btnF4.setBorder(null);
        pnlFondoTablero.add(btnF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 70, 70));

        btnF5.setBackground(new java.awt.Color(204, 204, 204));
        btnF5.setBorder(null);
        pnlFondoTablero.add(btnF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 70, 70));

        btnF6.setBackground(new java.awt.Color(126, 162, 214));
        btnF6.setBorder(null);
        pnlFondoTablero.add(btnF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 70, 70));

        btnF7.setBackground(new java.awt.Color(204, 204, 204));
        btnF7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnF7.setBorder(null);
        btnF7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF7ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, 70));

        btnF8.setBackground(new java.awt.Color(126, 162, 214));
        btnF8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilNegro.png"))); // NOI18N
        btnF8.setBorder(null);
        pnlFondoTablero.add(btnF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 70));

        btnE1.setBackground(new java.awt.Color(126, 162, 214));
        btnE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReyBlanco.png"))); // NOI18N
        btnE1.setBorder(null);
        pnlFondoTablero.add(btnE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 70, 70));

        btnE2.setBackground(new java.awt.Color(204, 204, 204));
        btnE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnE2.setBorder(null);
        btnE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 70, 70));

        btnE3.setBackground(new java.awt.Color(126, 162, 214));
        btnE3.setBorder(null);
        pnlFondoTablero.add(btnE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 70, 70));

        btnE4.setBackground(new java.awt.Color(204, 204, 204));
        btnE4.setBorder(null);
        pnlFondoTablero.add(btnE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, 70));

        btnE5.setBackground(new java.awt.Color(126, 162, 214));
        btnE5.setBorder(null);
        pnlFondoTablero.add(btnE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 70, 70));

        btnE6.setBackground(new java.awt.Color(204, 204, 204));
        btnE6.setBorder(null);
        pnlFondoTablero.add(btnE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 70, 70));

        btnE7.setBackground(new java.awt.Color(126, 162, 214));
        btnE7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnE7.setBorder(null);
        btnE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE7ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnE7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 70, 70));

        btnE8.setBackground(new java.awt.Color(204, 204, 204));
        btnE8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReyNegro.png"))); // NOI18N
        btnE8.setBorder(null);
        pnlFondoTablero.add(btnE8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 70, 70));

        btnD1.setBackground(new java.awt.Color(204, 204, 204));
        btnD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/DamaBlanca.png"))); // NOI18N
        btnD1.setBorder(null);
        pnlFondoTablero.add(btnD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 70, 70));

        btnD2.setBackground(new java.awt.Color(126, 162, 214));
        btnD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnD2.setBorder(null);
        btnD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 70, 70));

        btnD3.setBackground(new java.awt.Color(204, 204, 204));
        btnD3.setBorder(null);
        btnD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD3ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 70, 70));

        btnD4.setBackground(new java.awt.Color(126, 162, 214));
        btnD4.setBorder(null);
        pnlFondoTablero.add(btnD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, 70));

        btnD5.setBackground(new java.awt.Color(204, 204, 204));
        btnD5.setBorder(null);
        pnlFondoTablero.add(btnD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 70, 70));

        btnD6.setBackground(new java.awt.Color(126, 162, 214));
        btnD6.setBorder(null);
        pnlFondoTablero.add(btnD6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, 70));

        btnD7.setBackground(new java.awt.Color(204, 204, 204));
        btnD7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnD7.setBorder(null);
        btnD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD7ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnD7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, 70));

        btnD8.setBackground(new java.awt.Color(126, 162, 214));
        btnD8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/DamaNegra.png"))); // NOI18N
        btnD8.setBorder(null);
        pnlFondoTablero.add(btnD8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, 70));

        btnC1.setBackground(new java.awt.Color(126, 162, 214));
        btnC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilBlanco.png"))); // NOI18N
        btnC1.setBorder(null);
        pnlFondoTablero.add(btnC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 70, 70));

        btnC2.setBackground(new java.awt.Color(204, 204, 204));
        btnC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnC2.setBorder(null);
        btnC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 70, 70));

        btnC3.setBackground(new java.awt.Color(126, 162, 214));
        btnC3.setBorder(null);
        pnlFondoTablero.add(btnC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 70, 70));

        btnC4.setBackground(new java.awt.Color(204, 204, 204));
        btnC4.setBorder(null);
        pnlFondoTablero.add(btnC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 70, 70));

        btnC5.setBackground(new java.awt.Color(126, 162, 214));
        btnC5.setBorder(null);
        pnlFondoTablero.add(btnC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, 70));

        btnC6.setBackground(new java.awt.Color(204, 204, 204));
        btnC6.setBorder(null);
        pnlFondoTablero.add(btnC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 70));

        btnC7.setBackground(new java.awt.Color(126, 162, 214));
        btnC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnC7.setBorder(null);
        btnC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC7ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 70));

        btnC8.setBackground(new java.awt.Color(204, 204, 204));
        btnC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilNegro.png"))); // NOI18N
        btnC8.setBorder(null);
        pnlFondoTablero.add(btnC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 70));

        btnB1.setBackground(new java.awt.Color(204, 204, 204));
        btnB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoBlanco.png"))); // NOI18N
        btnB1.setBorder(null);
        pnlFondoTablero.add(btnB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 70, 70));

        btnB2.setBackground(new java.awt.Color(126, 162, 214));
        btnB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnB2.setBorder(null);
        btnB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 70, 70));

        btnB3.setBackground(new java.awt.Color(204, 204, 204));
        btnB3.setBorder(null);
        pnlFondoTablero.add(btnB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, 70));

        btnB4.setBackground(new java.awt.Color(126, 162, 214));
        btnB4.setBorder(null);
        pnlFondoTablero.add(btnB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 70, 70));

        btnB5.setBackground(new java.awt.Color(204, 204, 204));
        btnB5.setBorder(null);
        pnlFondoTablero.add(btnB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 70, 70));

        btnB6.setBackground(new java.awt.Color(126, 162, 214));
        btnB6.setBorder(null);
        pnlFondoTablero.add(btnB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, 70));

        btnB7.setBackground(new java.awt.Color(204, 204, 204));
        btnB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnB7.setBorder(null);
        btnB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB7ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, 70));

        btnB8.setBackground(new java.awt.Color(126, 162, 214));
        btnB8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoNegro.png"))); // NOI18N
        btnB8.setBorder(null);
        pnlFondoTablero.add(btnB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 70));

        btnA1.setBackground(new java.awt.Color(126, 162, 214));
        btnA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreBlanca.png"))); // NOI18N
        btnA1.setBorder(null);
        pnlFondoTablero.add(btnA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 70, 70));

        btnA2.setBackground(new java.awt.Color(204, 204, 204));
        btnA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnA2.setBorder(null);
        btnA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 70, 70));

        btnA3.setBackground(new java.awt.Color(126, 162, 214));
        btnA3.setBorder(null);
        pnlFondoTablero.add(btnA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 70, 70));

        btnA4.setBackground(new java.awt.Color(204, 204, 204));
        btnA4.setBorder(null);
        pnlFondoTablero.add(btnA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 70, 70));

        btnA5.setBackground(new java.awt.Color(126, 162, 214));
        btnA5.setBorder(null);
        pnlFondoTablero.add(btnA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 70, 70));

        btnA6.setBackground(new java.awt.Color(204, 204, 204));
        btnA6.setBorder(null);
        pnlFondoTablero.add(btnA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, 70));

        btnA7.setBackground(new java.awt.Color(126, 162, 214));
        btnA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnA7.setBorder(null);
        btnA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA7ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 70));

        btnA8.setBackground(new java.awt.Color(204, 204, 204));
        btnA8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreNegra.png"))); // NOI18N
        btnA8.setBorder(null);
        pnlFondoTablero.add(btnA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnlFondoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlFondoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF1ActionPerformed

    private void btnH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH1ActionPerformed
//peon blanco 
    private void btnH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH2ActionPerformed
        tableroA.setPosicionBotonesTablero(btnH2);
        System.out.println(tableroA.getPosicionActual());
        System.out.println(tableroA.retornarIdentificadorBotonesPorTablero());
        if (tableroA.retornarIdentificadorBotonesPorTablero().equals("peonBlanco")) {
            System.out.println("prueba de if");
        }
    }//GEN-LAST:event_btnH2ActionPerformed

    private void btnH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH3ActionPerformed
        // TODO add your handling code here:

        if (btnH2.isSelected() && obtenerPosicionTablero(posicionNueva).equals("peonBlanco")) {
            btnH3.setIcon(btnH2.getIcon());
            btnH2.setIcon(null);
        } else {
            System.out.println("prueba de no hay ese icono");
        }
    }//GEN-LAST:event_btnH3ActionPerformed

    private void btnH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnH4ActionPerformed

    private void btnD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD3ActionPerformed
//peones
    //peones blancos
    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnA2);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
        System.out.println(tableroA.retornarIdentificadorBotonesPorTablero()+" prueba de posicion clase tablero ");
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB2ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnB2);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
        System.out.println(tableroA.retornarIdentificadorBotonesPorTablero()+" prueba de posicion clase tablero ");
    }//GEN-LAST:event_btnB2ActionPerformed

    private void btnC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC2ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnC2);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnC2ActionPerformed

    private void btnD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD2ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnD2);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnD2ActionPerformed

    private void btnE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE2ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnE2);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnE2ActionPerformed

    private void btnF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF2ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnF2);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnF2ActionPerformed

    private void btnG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG2ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnG2);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnG2ActionPerformed
//peones negros
    private void btnA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA7ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnA7);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnA7ActionPerformed

    private void btnB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB7ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnB7);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnB7ActionPerformed

    private void btnC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC7ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnC7);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnC7ActionPerformed

    private void btnD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD7ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnD7);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnD7ActionPerformed

    private void btnE7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE7ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnE7);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnE7ActionPerformed

    private void btnF7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF7ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnF7);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnF7ActionPerformed

    private void btnG7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG7ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnG7);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnG7ActionPerformed

    private void btnH7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH7ActionPerformed
        // TODO add your handling code here:
        tableroA.setPosicionBotonesTablero(btnH7);
        System.out.println(tableroA.getPosicionActual() + " prueba de calse tablero");
    }//GEN-LAST:event_btnH7ActionPerformed

    /*public void quitarSeleccionTablero(){
        for(JToggleButton b: ){
            
        }
    }*/
    public String obtenerPosicionTablero(String p) {
        System.out.println(posicionActual);
        int x = Character.getNumericValue(posicionActual.charAt(0));
        int y = Character.getNumericValue(posicionActual.charAt(1));
        System.out.println(tablero[x][y]);
        String nombre = tablero[x][y];
        //String nombre = tableroA.getTablero()[x][y];
        return nombre;
    }

    private String getBotonPosicionString(Object boton) {
        if (boton == btnA8) {
            return "00";
        } else if (boton == btnB8) {
            return "01";
        } else if (boton == btnC8) {
            return "02";
        } else if (boton == btnD8) {
            return "03";
        } else if (boton == btnE8) {
            return "04";
        } else if (boton == btnF8) {
            return "05";
        } else if (boton == btnG8) {
            return "06";
        } else if (boton == btnH8) {
            return "07";
        } else if (boton == btnA7) {
            return "10";
        } else if (boton == btnB7) {
            return "11";
        } else if (boton == btnC7) {
            return "12";
        } else if (boton == btnD7) {
            return "13";
        } else if (boton == btnE7) {
            return "14";
        } else if (boton == btnF7) {
            return "15";
        } else if (boton == btnG7) {
            return "16";
        } else if (boton == btnH7) {
            return "17";
        } else if (boton == btnA6) {
            return "20";
        } else if (boton == btnB6) {
            return "21";
        } else if (boton == btnC6) {
            return "22";
        } else if (boton == btnD6) {
            return "23";
        } else if (boton == btnE6) {
            return "24";
        } else if (boton == btnF6) {
            return "25";
        } else if (boton == btnG6) {
            return "26";
        } else if (boton == btnH6) {
            return "27";
        } else if (boton == btnA5) {
            return "30";
        } else if (boton == btnB5) {
            return "31";
        } else if (boton == btnC5) {
            return "32";
        } else if (boton == btnD5) {
            return "33";
        } else if (boton == btnE5) {
            return "34";
        } else if (boton == btnF5) {
            return "35";
        } else if (boton == btnG5) {
            return "36";
        } else if (boton == btnH5) {
            return "37";
        } else if (boton == btnA4) {
            return "40";
        } else if (boton == btnB4) {
            return "41";
        } else if (boton == btnC4) {
            return "42";
        } else if (boton == btnD4) {
            return "43";
        } else if (boton == btnE4) {
            return "44";
        } else if (boton == btnF4) {
            return "45";
        } else if (boton == btnG4) {
            return "46";
        } else if (boton == btnH4) {
            return "47";
        } else if (boton == btnA3) {
            return "50";
        } else if (boton == btnB3) {
            return "51";
        } else if (boton == btnC3) {
            return "52";
        } else if (boton == btnD3) {
            return "53";
        } else if (boton == btnE3) {
            return "54";
        } else if (boton == btnF3) {
            return "55";
        } else if (boton == btnG3) {
            return "56";
        } else if (boton == btnH3) {
            return "57";
        } else if (boton == btnA2) {
            return "60";
        } else if (boton == btnB2) {
            return "61";
        } else if (boton == btnC2) {
            return "62";
        } else if (boton == btnD2) {
            return "63";
        } else if (boton == btnE2) {
            return "64";
        } else if (boton == btnF2) {
            return "65";
        } else if (boton == btnG2) {
            return "66";
        } else if (boton == btnH2) {
            return "67";
        } else if (boton == btnA1) {
            return "70";
        } else if (boton == btnB1) {
            return "71";
        } else if (boton == btnC1) {
            return "72";
        } else if (boton == btnD1) {
            return "73";
        } else if (boton == btnE1) {
            return "74";
        } else if (boton == btnF1) {
            return "75";
        } else if (boton == btnG1) {
            return "76";
        } else if (boton == btnH1) {
            return "77";
        }
        return null;
    }

    private void iniciarTablero() {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                tablero[i][j] = "";
            }
        }
        for (int i = 0; i < 8; i++) {
            tablero[1][i] = "peonNegro";
            tablero[6][i] = "peonBlanco";
        }
        tablero[0][0] = "torreNegro";
        tablero[0][1] = "caballoNegro";
        tablero[0][2] = "alfilNegro";
        tablero[0][3] = "damaNegro";
        tablero[0][4] = "reyNegro";
        tablero[0][5] = "alfilNegro";
        tablero[0][6] = "caballoNegro";
        tablero[0][7] = "torreNegro";

        tablero[7][0] = "torreBlanco";
        tablero[7][1] = "caballoBlanco";
        tablero[7][2] = "alfilBlanco";
        tablero[7][3] = "damaBlanco";
        tablero[7][4] = "reyBlanco";
        tablero[7][5] = "alfilBlanco";
        tablero[7][6] = "caballoBlanco";
        tablero[7][7] = "torreBlanco";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToggleButton btnA1;
    public static javax.swing.JToggleButton btnA2;
    public static javax.swing.JToggleButton btnA3;
    public static javax.swing.JToggleButton btnA4;
    public static javax.swing.JToggleButton btnA5;
    public static javax.swing.JToggleButton btnA6;
    public static javax.swing.JToggleButton btnA7;
    public static javax.swing.JToggleButton btnA8;
    public static javax.swing.JToggleButton btnB1;
    public static javax.swing.JToggleButton btnB2;
    public static javax.swing.JToggleButton btnB3;
    public static javax.swing.JToggleButton btnB4;
    public static javax.swing.JToggleButton btnB5;
    public static javax.swing.JToggleButton btnB6;
    public static javax.swing.JToggleButton btnB7;
    public static javax.swing.JToggleButton btnB8;
    public static javax.swing.JToggleButton btnC1;
    public static javax.swing.JToggleButton btnC2;
    public static javax.swing.JToggleButton btnC3;
    public static javax.swing.JToggleButton btnC4;
    public static javax.swing.JToggleButton btnC5;
    public static javax.swing.JToggleButton btnC6;
    public static javax.swing.JToggleButton btnC7;
    public static javax.swing.JToggleButton btnC8;
    public static javax.swing.JToggleButton btnD1;
    public static javax.swing.JToggleButton btnD2;
    public static javax.swing.JToggleButton btnD3;
    public static javax.swing.JToggleButton btnD4;
    public static javax.swing.JToggleButton btnD5;
    public static javax.swing.JToggleButton btnD6;
    public static javax.swing.JToggleButton btnD7;
    public static javax.swing.JToggleButton btnD8;
    public static javax.swing.JToggleButton btnE1;
    public static javax.swing.JToggleButton btnE2;
    public static javax.swing.JToggleButton btnE3;
    public static javax.swing.JToggleButton btnE4;
    public static javax.swing.JToggleButton btnE5;
    public static javax.swing.JToggleButton btnE6;
    public static javax.swing.JToggleButton btnE7;
    public static javax.swing.JToggleButton btnE8;
    public static javax.swing.JToggleButton btnF1;
    public static javax.swing.JToggleButton btnF2;
    public static javax.swing.JToggleButton btnF3;
    public static javax.swing.JToggleButton btnF4;
    public static javax.swing.JToggleButton btnF5;
    public static javax.swing.JToggleButton btnF6;
    public static javax.swing.JToggleButton btnF7;
    public static javax.swing.JToggleButton btnF8;
    public static javax.swing.JToggleButton btnG1;
    public static javax.swing.JToggleButton btnG2;
    public static javax.swing.JToggleButton btnG3;
    public static javax.swing.JToggleButton btnG4;
    public static javax.swing.JToggleButton btnG5;
    public static javax.swing.JToggleButton btnG6;
    public static javax.swing.JToggleButton btnG7;
    public static javax.swing.JToggleButton btnG8;
    public static javax.swing.JToggleButton btnH1;
    public static javax.swing.JToggleButton btnH2;
    public static javax.swing.JToggleButton btnH3;
    public static javax.swing.JToggleButton btnH4;
    public static javax.swing.JToggleButton btnH5;
    public static javax.swing.JToggleButton btnH6;
    public static javax.swing.JToggleButton btnH7;
    public static javax.swing.JToggleButton btnH8;
    private javax.swing.JPanel pnlFondoTablero;
    // End of variables declaration//GEN-END:variables
}
